# Generated by Django 5.2.10 on 2026-01-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="exit_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="k8s_job_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="job",
            name="k8s_namespace",
            field=models.CharField(default="k2p", max_length=64),
        ),
        migrations.AddField(
            model_name="job",
            name="result_key",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="job",
            name="stderr_tail",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="stdout_tail",
            field=models.TextField(blank=True),
        ),
    ]
